import 'package:floor/floor.dart';

//Here, we are saying to floor that this is a class that defines an entity
@entity
class Data {
  //id will be the primary key of the table. Moreover, it will be autogenerated.
  //id is nullable since it is autogenerated.
  @PrimaryKey(autoGenerate: true)
  final int? id; 

  //Height (cm)
  final double height;

  //Weight (kg)
  final double weight;

  //Hearth rate (bpm)
  final double hearthRate;

  //When the data is entered
  final DateTime dateTime;

  //HFA reference value
  final double? ReferenceValueHFA;

  //WFH reference value
  final double? ReferenceValueWFH;

  //Default constructor
  Data(this.id, this.height, this.weight, this.hearthRate, this.dateTime, this.ReferenceValueHFA, this.ReferenceValueWFH);
  
}//Data
